#region License
/*********************************************************************************
 * JsonErrorInfoParameterDisplayHelper.cs
 *
 * Copyright (c) 2004-2022 Henk Nicolai
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *
**********************************************************************************/
#endregion

using System;

namespace Eutherion.Text.Json
{
    /// <summary>
    /// Contains helper functions to generate default localized display values for common types of <see cref="JsonErrorInfoParameter{ParameterType}"/>.
    /// All parameter types generated by <see cref="JsonParser"/> are supported.
    /// </summary>
    public static class JsonErrorInfoParameterDisplayHelper
    {
        public static string GenerateCharacterErrorParameterString(char c)
            => StringLiteral.CharacterMustBeEscaped(c) ? StringLiteral.EscapedCharacterString(c) : Convert.ToString(c);

        public static string GetDisplayValue(JsonErrorInfoParameter parameter)
        {
            switch (parameter)
            {
                case JsonErrorInfoParameter<char> charParameter:
                    return GenerateCharacterErrorParameterString(charParameter.Value);
                case JsonErrorInfoParameter<string> stringParameter:
                    return stringParameter.Value;
                default:
                    throw new UnreachableException();
            }
        }
    }
}
